os: linux
dist: xenial
language: shell

services:
  - docker

env:
  - TAG=ubuntu16
  - TAG=ubuntu18

jobs:
  include:
    - stage: build
      script:
        - docker build -t builder --build-arg TAG=$TAG -f .build/Dockerfile .
        - docker run --rm builder -v ${TRAVIS_BUILD_DIR}/build:/iqlogger
        - ls -alh ${TRAVIS_BUILD_DIR}/build