sudo: required
dist: xenial
language: minimal

services:
  - docker

before_script:
  - docker build -t iqlogger_builder -f .docker/builder/Dockerfile .

script:
  - docker run --rm iqlogger_builder build/iqlogger --version

before_deploy:
  - docker run --rm iqlogger_builder -v ${TRAVIS_BUILD_DIR}/build:/project/build
  - ls -alh ${TRAVIS_BUILD_DIR}/build