os: linux
dist: xenial
language: shell

services:
  - docker

jobs:
  include:
    - env:
        - TAG=ubuntu16
    - env:
        - TAG=ubuntu18

script:
  - docker build -t builder -f .build/Dockerfile .
  - docker run --rm builder -v ${TRAVIS_BUILD_DIR}/build:/iqlogger
  - ls -alh ${TRAVIS_BUILD_DIR}/build