os: linux
dist: xenial
language: shell

services:
  - docker

jobs:
  include:
    - env:
        - TAG=ubuntu16
        - ARCH=amd64
        - UBUNTU=xenial
    - env:
        - TAG=ubuntu18
        - ARCH=amd64
        - UBUNTU=bionic

script:
  - export VERSION=`cat ./version`
  - docker build -t builder --build-arg VERSION="$VERSION" --build-arg TAG="$TAG" --build-arg ARCH="$ARCH" --build-arg UBUNTU="$UBUNTU" --build-arg TRAVIS_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER" --build-arg TRAVIS_BRANCH="$TRAVIS_BRANCH" --build-arg TRAVIS_COMMIT="$TRAVIS_COMMIT" --build-arg TRAVIS_COMMIT_MESSAGE="$TRAVIS_COMMIT_MESSAGE" --build-arg USER="$USER" -f .build/Dockerfile .
  - docker create --name builder builder
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - docker cp builder:/iqlogger/iqlogger ${TRAVIS_BUILD_DIR}/build/
  - docker cp builder:/iqlogger/.build_deb/${TAG}/iqlogger_$VERSION-$UBUNTU_$ARCH.deb ${TRAVIS_BUILD_DIR}/build/
  - docker rm builder
  - ls -alh ${TRAVIS_BUILD_DIR}/build