os: linux
dist: xenial
language: shell

services:
  - docker

jobs:
  include:
    - env:
        - TAG=ubuntu16
    - env:
        - TAG=ubuntu18

script:
  - docker build -t builder --build-arg TAG=$TAG -f .build/Dockerfile .
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/iqlogger/build builder
  - ls -alh ${TRAVIS_BUILD_DIR}/build