os: linux
dist: xenial
language: shell

services:
  - docker

jobs:
  include:
    - env:
        - TAG=ubuntu16
    - env:
        - TAG=ubuntu18

script:
  - docker build -t builder --build-arg TAG=$TAG -f .build/Dockerfile .
  - docker create --name builder builder
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - docker cp builder:/iqlogger/iqlogger ${TRAVIS_BUILD_DIR}/build/
  - docker cp builder:/iqlogger/.build_deb/${TAG}/*.deb ${TRAVIS_BUILD_DIR}/build/
  - docker rm builder
  - ls -alh ${TRAVIS_BUILD_DIR}/build